<?php

namespace ContainerN0IJP0m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInstructorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.CHABmpF.App\Entity\Instructor' shared service.
     *
     * @return \App\Entity\Instructor
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.CHABmpF": it references class "App\\Entity\\Instructor" but no such service exists.');
    }
}
