<?php

namespace ContainerVr3wL1t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Value_J9NKioService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.value.j9_NKio' shared service.
     *
     * @return \mixed
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.value.j9_NKio'] = \current([0 => $container->getEnv('STRIPE_SK')]);
    }
}
