<?php

namespace ContainerVr3wL1t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VLY43fPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vLY43fP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vLY43fP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'donation' => ['privates', '.errored..service_locator.vLY43fP.App\\Entity\\Donation', NULL, 'Cannot autowire service ".service_locator.vLY43fP": it references class "App\\Entity\\Donation" but no such service exists.'],
        ], [
            'donation' => 'App\\Entity\\Donation',
        ]);
    }
}
