<?php

namespace ContainerVr3wL1t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FAlyFnJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fAlyFnJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fAlyFnJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'course' => ['privates', '.errored..service_locator.fAlyFnJ.App\\Entity\\Course', NULL, 'Cannot autowire service ".service_locator.fAlyFnJ": it references class "App\\Entity\\Course" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'course' => 'App\\Entity\\Course',
            'entityManager' => '?',
        ]);
    }
}
