<?php

namespace ContainerVr3wL1t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5ki9615Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5ki9615' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5ki9615'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'admin' => ['privates', '.errored..service_locator.5ki9615.App\\Entity\\Admin', NULL, 'Cannot autowire service ".service_locator.5ki9615": it references class "App\\Entity\\Admin" but no such service exists.'],
            'registry' => ['services', 'doctrine', 'getDoctrineService', false],
            'twilioService' => ['privates', 'App\\Service\\TwilioService', 'getTwilioServiceService', true],
        ], [
            'admin' => 'App\\Entity\\Admin',
            'registry' => '?',
            'twilioService' => 'App\\Service\\TwilioService',
        ]);
    }
}
