<?php

namespace ContainerVr3wL1t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XkzpdZcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XkzpdZc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XkzpdZc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'post' => ['privates', '.errored..service_locator.XkzpdZc.App\\Entity\\Post', NULL, 'Cannot autowire service ".service_locator.XkzpdZc": it references class "App\\Entity\\Post" but no such service exists.'],
            'repo' => ['privates', 'App\\Repository\\CmntRepository', 'getCmntRepositoryService', true],
        ], [
            'post' => 'App\\Entity\\Post',
            'repo' => 'App\\Repository\\CmntRepository',
        ]);
    }
}
