<?php

namespace ContainerVr3wL1t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZtAgefAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ztAgefA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ztAgefA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'chapitre' => ['privates', '.errored..service_locator.ztAgefA.App\\Entity\\Chapitre', NULL, 'Cannot autowire service ".service_locator.ztAgefA": it references class "App\\Entity\\Chapitre" but no such service exists.'],
        ], [
            'chapitre' => 'App\\Entity\\Chapitre',
        ]);
    }
}
