<?php

namespace ContainerVr3wL1t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ir32RfBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ir32RfB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ir32RfB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'student' => ['privates', '.errored..service_locator.Ir32RfB.App\\Entity\\Student', NULL, 'Cannot autowire service ".service_locator.Ir32RfB": it references class "App\\Entity\\Student" but no such service exists.'],
        ], [
            'student' => 'App\\Entity\\Student',
        ]);
    }
}
