<?php

namespace ContainerVr3wL1t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7_XJXtrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7.xJXtr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7.xJXtr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'chapitre' => ['privates', '.errored..service_locator.7.xJXtr.App\\Entity\\Chapitre', NULL, 'Cannot autowire service ".service_locator.7.xJXtr": it references class "App\\Entity\\Chapitre" but no such service exists.'],
            'chapitreFileRepository' => ['privates', 'App\\Repository\\ChapitrefileRepository', 'getChapitrefileRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'chapitre' => 'App\\Entity\\Chapitre',
            'chapitreFileRepository' => 'App\\Repository\\ChapitrefileRepository',
            'entityManager' => '?',
        ]);
    }
}
