<?php

namespace ContainerVr3wL1t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OMCDP_RService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OMCDP.r' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OMCDP.r'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cmnt' => ['privates', '.errored..service_locator.OMCDP.r.App\\Entity\\Cmnt', NULL, 'Cannot autowire service ".service_locator.OMCDP.r": it references class "App\\Entity\\Cmnt" but no such service exists.'],
        ], [
            'cmnt' => 'App\\Entity\\Cmnt',
        ]);
    }
}
