<?php

namespace ContainerVr3wL1t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChapitre3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.SX1_dHg.App\Entity\Chapitre' shared service.
     *
     * @return \App\Entity\Chapitre
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.SX1_dHg": it references class "App\\Entity\\Chapitre" but no such service exists.');
    }
}
