<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTMlx3sr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTMlx3sr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTMlx3sr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTMlx3sr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTMlx3sr\App_KernelDevDebugContainer([
    'container.build_hash' => 'TMlx3sr',
    'container.build_id' => '124943ee',
    'container.build_time' => 1701107093,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTMlx3sr');
