<?php

namespace ContainerCoiiPi9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_68HfYF2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.68HfYF2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.68HfYF2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'chapitre' => ['privates', '.errored..service_locator.68HfYF2.App\\Entity\\Chapitre', NULL, 'Cannot autowire service ".service_locator.68HfYF2": it references class "App\\Entity\\Chapitre" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repo' => ['privates', 'App\\Repository\\ChapitrequizzRepository', 'getChapitrequizzRepositoryService', true],
        ], [
            'chapitre' => 'App\\Entity\\Chapitre',
            'entityManager' => '?',
            'repo' => 'App\\Repository\\ChapitrequizzRepository',
        ]);
    }
}
