<?php

namespace ContainerCoiiPi9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IquzHCTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iquzHCT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iquzHCT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'admin' => ['privates', '.errored..service_locator.iquzHCT.App\\Entity\\Admin', NULL, 'Cannot autowire service ".service_locator.iquzHCT": it references class "App\\Entity\\Admin" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'tokenStorage' => ['services', '.container.private.security.token_storage', 'get_Container_Private_Security_TokenStorageService', false],
        ], [
            'admin' => 'App\\Entity\\Admin',
            'entityManager' => '?',
            'tokenStorage' => '?',
        ]);
    }
}
