<?php

namespace ContainerCoiiPi9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Yhx7W1nService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Yhx7W1n' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Yhx7W1n'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'review' => ['privates', '.errored..service_locator.Yhx7W1n.App\\Entity\\Review', NULL, 'Cannot autowire service ".service_locator.Yhx7W1n": it references class "App\\Entity\\Review" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'review' => 'App\\Entity\\Review',
        ]);
    }
}
