<?php

namespace ContainerCoiiPi9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MBlpluEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MBlpluE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MBlpluE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'donationRepository' => ['privates', 'App\\Repository\\DonationRepository', 'getDonationRepositoryService', true],
        ], [
            'donationRepository' => 'App\\Repository\\DonationRepository',
        ]);
    }
}
