<?php

namespace ContainerCoiiPi9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Vsc2fmmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vsc2fmm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vsc2fmm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'donation' => ['privates', '.errored..service_locator.vsc2fmm.App\\Entity\\Donation', NULL, 'Cannot autowire service ".service_locator.vsc2fmm": it references class "App\\Entity\\Donation" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'donation' => 'App\\Entity\\Donation',
            'entityManager' => '?',
        ]);
    }
}
