<?php

namespace ContainerCoiiPi9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PAyF4iXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pAyF4iX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pAyF4iX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'instructor' => ['privates', '.errored..service_locator.pAyF4iX.App\\Entity\\Instructor', NULL, 'Cannot autowire service ".service_locator.pAyF4iX": it references class "App\\Entity\\Instructor" but no such service exists.'],
            'registry' => ['services', 'doctrine', 'getDoctrineService', false],
            'twilioService' => ['privates', 'App\\Service\\TwilioService', 'getTwilioServiceService', true],
        ], [
            'instructor' => 'App\\Entity\\Instructor',
            'registry' => '?',
            'twilioService' => 'App\\Service\\TwilioService',
        ]);
    }
}
