<?php

namespace ContainerCoiiPi9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4y_CzfhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4y.Czfh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4y.Czfh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cmntRepo' => ['privates', 'App\\Repository\\CmntRepository', 'getCmntRepositoryService', true],
            'entityManager' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'cmntRepo' => 'App\\Repository\\CmntRepository',
            'entityManager' => '?',
        ]);
    }
}
