<?php

namespace ContainerCoiiPi9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JUDtbBjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jUDtbBj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jUDtbBj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'instructorRepository' => ['privates', 'App\\Repository\\InstructorRepository', 'getInstructorRepositoryService', true],
        ], [
            'instructorRepository' => 'App\\Repository\\InstructorRepository',
        ]);
    }
}
