<?php

namespace ContainerCoiiPi9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LShnJVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lShnJV_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lShnJV_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'course' => ['privates', '.errored..service_locator.lShnJV_.App\\Entity\\Course', NULL, 'Cannot autowire service ".service_locator.lShnJV_": it references class "App\\Entity\\Course" but no such service exists.'],
        ], [
            'course' => 'App\\Entity\\Course',
        ]);
    }
}
