<?php

namespace ContainerCoiiPi9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChapitre4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ztAgefA.App\Entity\Chapitre' shared service.
     *
     * @return \App\Entity\Chapitre
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ztAgefA": it references class "App\\Entity\\Chapitre" but no such service exists.');
    }
}
