<?php

namespace ContainerCoiiPi9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCmnt2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.OMCDP.r.App\Entity\Cmnt' shared service.
     *
     * @return \App\Entity\Cmnt
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.OMCDP.r": it references class "App\\Entity\\Cmnt" but no such service exists.');
    }
}
