<?php

namespace ContainerCoiiPi9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDonationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.vLY43fP.App\Entity\Donation' shared service.
     *
     * @return \App\Entity\Donation
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.vLY43fP": it references class "App\\Entity\\Donation" but no such service exists.');
    }
}
