<?php

namespace ContainerCoiiPi9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayment2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.tPSEDJD.App\Entity\Payment' shared service.
     *
     * @return \App\Entity\Payment
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.tPSEDJD": it references class "App\\Entity\\Payment" but no such service exists.');
    }
}
