<?php

namespace ContainerCoiiPi9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReview2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Yhx7W1n.App\Entity\Review' shared service.
     *
     * @return \App\Entity\Review
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Yhx7W1n": it references class "App\\Entity\\Review" but no such service exists.');
    }
}
