<?php

namespace ContainerCoiiPi9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStudent2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.8qREtcW.App\Entity\Student' shared service.
     *
     * @return \App\Entity\Student
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.8qREtcW": it references class "App\\Entity\\Student" but no such service exists.');
    }
}
