<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVr3wL1t\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVr3wL1t/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVr3wL1t.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVr3wL1t\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVr3wL1t\App_KernelDevDebugContainer([
    'container.build_hash' => 'Vr3wL1t',
    'container.build_id' => '7ec1aaf8',
    'container.build_time' => 1736090157,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVr3wL1t');
